name: GitHub Actions Testing

on:
  push:
    branches: [main, dev/*, create-github-actions]
  pull_request:
    branches: [master, dev/*, create-github-actions]

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    strategy:
      matrix:
        node-version: [22.1.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:ci
      - name: Run SonarLint
        run: npm run lint
